apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-luxembourg-cidr
  namespace: luxembourg
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 100.0.26.0/24
    ports:
    - protocol: TCP
      port: 80